// Attribute translation tables: HTML attribute name -> React prop name + value kind.
//
// kinds:
//   str      string value, emitted as-is
//   bool     boolean attribute (presence == true)
//   num      integer-typed React prop (falls back to a raw attribute when not an integer)
//   boolish  "true"/"false" string props (draggable, spellCheck, contentEditable)

/** @type {Record<string, [string, 'str'|'bool'|'num'|'boolish']>} */
export const HTML_ATTRS = {
  "accept": ["accept", "str"],
  "accept-charset": ["acceptCharset", "str"],
  "accesskey": ["accessKey", "str"],
  "action": ["action", "str"],
  "allow": ["allow", "str"],
  "allowfullscreen": ["allowFullScreen", "bool"],
  "alt": ["alt", "str"],
  "as": ["as", "str"],
  "async": ["async", "bool"],
  "autocapitalize": ["autoCapitalize", "str"],
  "autocomplete": ["autoComplete", "str"],
  "autofocus": ["autoFocus", "bool"],
  "autoplay": ["autoPlay", "bool"],
  "capture": ["capture", "str"],
  "cellpadding": ["cellPadding", "str"],
  "cellspacing": ["cellSpacing", "str"],
  "charset": ["charSet", "str"],
  "checked": ["defaultChecked", "bool"],
  "cite": ["cite", "str"],
  "class": ["className", "str"],
  "cols": ["cols", "num"],
  "colspan": ["colSpan", "num"],
  "content": ["content", "str"],
  "contenteditable": ["contentEditable", "boolish"],
  "controls": ["controls", "bool"],
  "controlslist": ["controlsList", "str"],
  "coords": ["coords", "str"],
  "crossorigin": ["crossOrigin", "str"],
  "data": ["data", "str"],
  "datetime": ["dateTime", "str"],
  "default": ["default", "bool"],
  "defer": ["defer", "bool"],
  "dir": ["dir", "str"],
  "disabled": ["disabled", "bool"],
  "disablepictureinpicture": ["disablePictureInPicture", "bool"],
  "disableremoteplayback": ["disableRemotePlayback", "bool"],
  "download": ["download", "str"],
  "draggable": ["draggable", "boolish"],
  "enctype": ["encType", "str"],
  "enterkeyhint": ["enterKeyHint", "str"],
  "fetchpriority": ["fetchPriority", "str"],
  "for": ["htmlFor", "str"],
  "form": ["form", "str"],
  "formaction": ["formAction", "str"],
  "formenctype": ["formEncType", "str"],
  "formmethod": ["formMethod", "str"],
  "formnovalidate": ["formNoValidate", "bool"],
  "formtarget": ["formTarget", "str"],
  "frameborder": ["frameBorder", "str"],
  "headers": ["headers", "str"],
  "height": ["height", "str"],
  "hidden": ["hidden", "bool"],
  "high": ["high", "str"],
  "href": ["href", "str"],
  "hreflang": ["hrefLang", "str"],
  "http-equiv": ["httpEquiv", "str"],
  "id": ["id", "str"],
  "inert": ["inert", "bool"],
  "inputmode": ["inputMode", "str"],
  "integrity": ["integrity", "str"],
  "is": ["is", "str"],
  "itemid": ["itemID", "str"],
  "itemprop": ["itemProp", "str"],
  "itemref": ["itemRef", "str"],
  "itemscope": ["itemScope", "bool"],
  "itemtype": ["itemType", "str"],
  "kind": ["kind", "str"],
  "label": ["label", "str"],
  "lang": ["lang", "str"],
  "list": ["list", "str"],
  "loading": ["loading", "str"],
  "loop": ["loop", "bool"],
  "low": ["low", "str"],
  "marginheight": ["marginHeight", "str"],
  "marginwidth": ["marginWidth", "str"],
  "max": ["max", "str"],
  "maxlength": ["maxLength", "num"],
  "media": ["media", "str"],
  "method": ["method", "str"],
  "min": ["min", "str"],
  "minlength": ["minLength", "num"],
  "multiple": ["multiple", "bool"],
  "muted": ["muted", "bool"],
  "name": ["name", "str"],
  "nomodule": ["noModule", "bool"],
  "nonce": ["nonce", "str"],
  "novalidate": ["noValidate", "bool"],
  "open": ["open", "bool"],
  "optimum": ["optimum", "str"],
  "pattern": ["pattern", "str"],
  "placeholder": ["placeholder", "str"],
  "playsinline": ["playsInline", "bool"],
  "popover": ["popover", "str"],
  "popovertarget": ["popoverTarget", "str"],
  "popovertargetaction": ["popoverTargetAction", "str"],
  "poster": ["poster", "str"],
  "preload": ["preload", "str"],
  "readonly": ["readOnly", "bool"],
  "referrerpolicy": ["referrerPolicy", "str"],
  "rel": ["rel", "str"],
  "required": ["required", "bool"],
  "reversed": ["reversed", "bool"],
  "role": ["role", "str"],
  "rows": ["rows", "num"],
  "rowspan": ["rowSpan", "num"],
  "sandbox": ["sandbox", "str"],
  "scope": ["scope", "str"],
  "scrolling": ["scrolling", "str"],
  "shape": ["shape", "str"],
  "size": ["size", "num"],
  "sizes": ["sizes", "str"],
  "slot": ["slot", "str"],
  "span": ["span", "num"],
  "spellcheck": ["spellCheck", "boolish"],
  "src": ["src", "str"],
  "srcdoc": ["srcDoc", "str"],
  "srclang": ["srcLang", "str"],
  "srcset": ["srcSet", "str"],
  "start": ["start", "num"],
  "step": ["step", "str"],
  "summary": ["summary", "str"],
  "tabindex": ["tabIndex", "num"],
  "target": ["target", "str"],
  "title": ["title", "str"],
  "translate": ["translate", "str"],
  "type": ["type", "str"],
  "usemap": ["useMap", "str"],
  "value": ["value", "str"],
  "width": ["width", "str"],
  "wrap": ["wrap", "str"],
};

/** Attributes of foreign (SVG/MathML) elements that do not follow the camelCase rule. */
export const SVG_SPECIAL_ATTRS = {
  "class": "className",
  "tabindex": "tabIndex",
  "xlink:href": "xlinkHref",
  "xlink:title": "xlinkTitle",
  "xlink:show": "xlinkShow",
  "xlink:role": "xlinkRole",
  "xlink:arcrole": "xlinkArcrole",
  "xlink:actuate": "xlinkActuate",
  "xlink:type": "xlinkType",
  "xml:space": "xmlSpace",
  "xml:lang": "xmlLang",
  "xml:base": "xmlBase",
  "xmlns:xlink": "xmlnsXlink",
};

/** Elements whose whitespace-only text children are insignificant and invalid in React. */
export const WHITESPACE_INSENSITIVE_PARENTS = new Set([
  "table", "thead", "tbody", "tfoot", "tr", "colgroup", "select", "optgroup", "datalist",
  "html", "head", "frameset", "video", "audio", "picture",
]);

/** Block-level elements: leading/trailing whitespace-only children never render. */
export const BLOCK_TAGS = new Set([
  "address", "article", "aside", "blockquote", "body", "dd", "details", "dialog", "div", "dl", "dt",
  "fieldset", "figcaption", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5", "h6", "header",
  "hgroup", "hr", "li", "main", "nav", "ol", "p", "section", "summary", "table", "td", "th", "ul",
  "noscript", "template", "svg", "g", "defs", "linearGradient", "radialGradient", "clipPath", "mask",
  "pattern", "filter", "symbol", "marker", "button", "option",
]);

export const VOID_ELEMENTS = new Set([
  "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr",
]);

/** Input types for which `value` is a label/submission value rather than editable state. */
export const INPUT_VALUE_ATTR_TYPES = new Set(["checkbox", "radio", "button", "submit", "reset", "image", "hidden"]);
