/**
 * Entry for public/config.js (classic script loaded by every legacy page).
 *
 * Generated by scripts/build-runtime.mjs; do not edit public/config.js by hand.
 *
 * Runs the sections of the legacy ui/config.js in their original order. Each
 * section was a separate top-level IIFE there:
 *  - api-base, console-hygiene, html-sanitizer, auth-shim and theme wrap their
 *    whole body in try/catch and swallow errors themselves (kept inside each
 *    `install()`).
 *  - tune-ai-flags, nav-dropdowns and tune-ai-widget had no try/catch. A throw
 *    there is still surfaced as an uncaught error (window "error" event /
 *    console), but it no longer aborts the sections that follow.
 *
 * Idempotent: if this bundle is executed a second time on the same page (some
 * pages include config.js twice) the second execution does nothing. This is
 * the only intentional behaviour change from the legacy script, which would
 * otherwise, for example, wrap window.fetch twice.
 */
import { installConfigRuntime } from './runtime';

installConfigRuntime();
