#!/usr/bin/env node
/**
 * Builds the classic runtime scripts that legacy pages load with
 * <script src="/config.js"> and <script src="/auth.js">:
 *
 *   src/runtime/config/index.ts -> public/config.js
 *   src/runtime/auth/index.ts   -> public/auth.js
 *
 * Output is a readable (unminified) IIFE targeting ES2018 for the browser.
 * `process.env.NEXT_PUBLIC_API_BASE` is inlined at bundle time; it is read from
 * the shell environment, then frontend/.env.local, then frontend/.env, and
 * defaults to 'http://0.0.0.0:10000' when unset or empty.
 *
 * Usage (from frontend/):
 *   node scripts/build-runtime.mjs           # one-off build
 *   node scripts/build-runtime.mjs --watch   # rebuild on change
 */
import { existsSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const FRONTEND_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEFAULT_API_BASE = 'http://0.0.0.0:10000';

const ENTRIES = [
  { entry: 'src/runtime/config/index.ts', outfile: 'public/config.js' },
  { entry: 'src/runtime/auth/index.ts', outfile: 'public/auth.js' },
];

/**
 * Minimal dotenv parser (no dependencies): KEY=VALUE lines, optional `export `
 * prefix, `#` comments, single/double/back-quoted values (`\n` expanded inside
 * double quotes), and trailing ` # comment` on unquoted values.
 */
export function parseEnv(source) {
  const out = {};
  for (const rawLine of source.split(/\r?\n/)) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice('export '.length).trim();
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_.-]*$/.test(key)) continue;
    let value = line.slice(eq + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'" || quote === '`') && value.length >= 2 && value.endsWith(quote)) {
      value = value.slice(1, -1);
      if (quote === '"') value = value.replace(/\\n/g, '\n').replace(/\\r/g, '\r');
    } else {
      const hash = value.search(/\s#/);
      if (hash !== -1) value = value.slice(0, hash).trim();
    }
    out[key] = value;
  }
  return out;
}

function readEnvFile(name) {
  const file = path.join(FRONTEND_DIR, name);
  if (!existsSync(file)) return {};
  return parseEnv(readFileSync(file, 'utf8'));
}

/** Shell env wins over .env.local, which wins over .env (Next.js precedence). */
export function resolveApiBase() {
  const fileEnv = { ...readEnvFile('.env'), ...readEnvFile('.env.local') };
  const fromShell = process.env.NEXT_PUBLIC_API_BASE;
  const raw = fromShell !== undefined ? fromShell : fileEnv.NEXT_PUBLIC_API_BASE;
  const value = String(raw ?? '').trim();
  return value || DEFAULT_API_BASE;
}

function buildOptions(apiBase, { entry, outfile }, plugins = []) {
  return {
    absWorkingDir: FRONTEND_DIR,
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'iife',
    target: 'es2018',
    platform: 'browser',
    minify: false,
    legalComments: 'none',
    sourcemap: false,
    logLevel: 'warning',
    // The legacy ui/config.js and ui/auth.js ran as sloppy-mode classic scripts.
    // Don't let tsconfig.json's `strict` make esbuild prepend "use strict";
    // type checking stays strict via `tsc`.
    tsconfigRaw: { compilerOptions: { alwaysStrict: false } },
    banner: {
      js: `/* Generated by scripts/build-runtime.mjs from ${path.dirname(entry)} -- do not edit. */`,
    },
    define: {
      'process.env.NEXT_PUBLIC_API_BASE': JSON.stringify(apiBase),
    },
    plugins,
  };
}

function kb(file) {
  try {
    return `${(statSync(path.join(FRONTEND_DIR, file)).size / 1024).toFixed(1)} kB`;
  } catch {
    return '?';
  }
}

function summary(apiBase, ms, prefix = 'built') {
  const files = ENTRIES.map((e) => `${e.outfile} (${kb(e.outfile)})`).join(', ');
  return `[build-runtime] ${prefix} ${files} with NEXT_PUBLIC_API_BASE=${apiBase} in ${ms}ms`;
}

async function buildOnce() {
  const apiBase = resolveApiBase();
  const started = Date.now();
  await Promise.all(ENTRIES.map((e) => esbuild.build(buildOptions(apiBase, e))));
  console.log(summary(apiBase, Date.now() - started));
}

async function watch() {
  const apiBase = resolveApiBase();
  const contexts = await Promise.all(
    ENTRIES.map((e) => {
      let started = Date.now();
      const reporter = {
        name: 'build-runtime-reporter',
        setup(build) {
          build.onStart(() => { started = Date.now(); });
          build.onEnd((result) => {
            const status = result.errors.length ? `failed (${result.errors.length} error(s))` : `${e.outfile} (${kb(e.outfile)})`;
            console.log(`[build-runtime] ${new Date().toLocaleTimeString()} ${status} in ${Date.now() - started}ms`);
          });
        },
      };
      return esbuild.context(buildOptions(apiBase, e, [reporter]));
    }),
  );
  await Promise.all(contexts.map((ctx) => ctx.watch()));
  console.log(`[build-runtime] watching src/runtime with NEXT_PUBLIC_API_BASE=${apiBase} (Ctrl+C to stop)`);
  const stop = async () => {
    await Promise.all(contexts.map((ctx) => ctx.dispose()));
    process.exit(0);
  };
  process.on('SIGINT', stop);
  process.on('SIGTERM', stop);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const run = process.argv.includes('--watch') ? watch : buildOnce;
  run().catch((err) => {
    console.error('[build-runtime] failed:', err && err.message ? err.message : err);
    process.exit(1);
  });
}
