/**
 * Entry for public/auth.js (classic script: navbar auth UI helper).
 *
 * Generated by scripts/build-runtime.mjs; do not edit public/auth.js by hand.
 *
 * Idempotent: a second execution on the same page (some pages include auth.js
 * twice) is a no-op. The legacy script already guarded init() with
 * `window.__PX_AUTH_INIT_DONE`; this additionally skips re-assigning
 * `window.__PX_NAV_APPLY` and re-reading the API base. No try/catch, matching
 * the original IIFE.
 */
import { install } from './nav-auth';

if (!window.__PX_RUNTIME_AUTH_INSTALLED) {
  window.__PX_RUNTIME_AUTH_INSTALLED = true;
  install();
}
