// Generated by scripts/convert-ui — custom elements used by the converted pages.
import type { HTMLAttributes } from "react";

type LegacyCustomElementProps = HTMLAttributes<HTMLElement> & { [attribute: string]: unknown };

declare module "react" {
  // Inline styles in the legacy markup set CSS custom properties (--pct, --tw-ring-color…).
  interface CSSProperties {
    [customProperty: `--${string}`]: string | number | undefined;
  }

  namespace JSX {
    interface IntrinsicElements {
      "dotlottie-wc": LegacyCustomElementProps;
    }
  }
}
